/** Route path constants — single source of truth for all route URLs. */
export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  ABOUT: '/about',
  DASHBOARD: '/dashboard',
  DAILY_TASKS: '/daily',
  WEEKLY_TASKS: '/weekly',
  MONTHLY_GOALS: '/monthly',
  ANALYTICS: '/analytics',
  CALENDAR: '/calendar',
  HISTORY: '/history',
  HISTORY_MONTH: '/history/:year/:month',
  FRIENDS: '/friends',
  FRIEND_PROFILE: '/friends/:id',
  CHALLENGES: '/challenges',
  CREATE_CHALLENGE: '/challenges/create',
  CHALLENGE_DETAIL: '/challenges/:id',
  NOTIFICATIONS: '/notifications',
  ACHIEVEMENTS: '/achievements',
  LEADERBOARD: '/leaderboard',
  PROFILE: '/profile',
  SETTINGS: '/settings',
} as const;
